language: php
php:
  - "5.6.30"
env:
  - CI_ENV=unit_testing CI_ROOTED=true
install:
  - composer require squizlabs/php_codesniffer:2.9.1
  - composer require codeclimate/php-test-reporter --dev
  - phpenv rehash
script:
 - find / -iname phpcs
 - bash -xe test-everything.sh
