language: php
php:
  - "5.6"
env:
  - CI_ENV=unit_testing CI_ROOTED=true
install:
# - pyrus install pear/PHP_CodeSniffer-2.9.1
- composer require squizlabs/php_codesniffer:2.9.1
- composer require codeclimate/php-test-reporter --dev
- phpenv rehash
script:
 - bash -xe test-everything.sh
